#!/bin/sh

### BEGIN INIT INFO
# Provides:          hsp-fo-app
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: hsp-fo-app
# Description:       hsp-fo-app
### END INIT INFO

NAME=hsp-fo-app
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
WORKDIR=/usr/local/SBB/usr/local/hsp-fo-app
CONFDIR=/etc/SBB/$NAME
DAEMON=`which node`
DAEMONARGS="server/start.js"
USER=$NAME
GROUP=$NAME
PIDFILE=/var/run/SBB/$NAME/$NAME.pid
LOGFILE=/var/log/SBB/$NAME/$NAME.log

# Include functions 
set -e
. /lib/lsb/init-functions

# source main config file
. $CONFDIR/$NAME.conf

start() {

  # HSP_ENVIRONMENT is defined in $CONFDIR/$NAME.conf
  case "$HSP_ENVIRONMENT" in
    dev)
      . $CONFDIR/env-dev.sh
      ;;
    test)
      . $CONFDIR/env-test.sh
      ;;
    stage)
      . $CONFDIR/env-stage.sh
      ;;
    prod)
      . $CONFDIR/env-prod.sh
      ;;
    *)
      echo "Error in /etc/default/$NAME: expect HSP_ENVIRONMENT={dev|test|stage|prod}" >&2
      exit 1
      ;;
  esac

  printf "Starting '$NAME'... "
  start-stop-daemon --start --quiet \
        --chuid "$USER" \
        --name "$NAME" \
        --make-pidfile --pidfile "$PIDFILE" \
        --background --no-close \
        --startas "$DAEMON" \
        --chdir "$WORKDIR" \
        -- "$DAEMONARGS" \
        >> "$LOGFILE" 2>&1
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat $PIDFILE 2>/dev/null` ] || \
  while test -d /proc/$(cat $PIDFILE); do
    killtree $(cat $PIDFILE) 15
    sleep 0.5
  done 
  [ -z `cat $PIDFILE 2>/dev/null` ] || rm $PIDFILE
  printf "done\n"
}

status() {
#  status_of_proc $PIDFILE "" $NAME && exit 0 || exit $?
  pid=$(cat $PIDFILE)
  ps -p "$pid" && echo "Running... " || { echo "Not running (process $pid not found)"; exit 1; }
  exit 0
}



case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0