#!/bin/sh

set -e

if which initctl >/dev/null && initctl version | grep -q upstart; then
    # Using upstart
    initctl stop hsp-fo-app || true
else
    # Using SysV init scripts
    service hsp-fo-app stop || true
fi
